# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df4bc0d55b27d18e6f923d1c9210fc8a09dc0d9ae5b0a9b427f7fa79b1882e93061c6dc52c2e05add883f854911c0c51f132814044646f22cd1cf1f51f84147b

test:
  secret_key_base: 70d4e512daa24d124f2197efc2229a15fb1c800ef920c8b9aa5ca58379339c8145076b70ffe26aba25fef80726811b477af70f9d16577f048e053569fea0723c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
